name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Run Rust tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone the code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10

      - name: Install Rust
        run: rustup update stable && rustup default stable

      - name: Run tests
        run: make test
